<a href="https://colab.research.google.com/github/lilianabs/ml-notebooks/blob/main/Getting_Started_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.6


In [5]:
# Create array

a = np.array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [6]:
a.shape

(3,)

In [8]:
# Check the data type
a.dtype

dtype('int64')

In [10]:
# Check number of dimensions

a.ndim

1

In [11]:
# Total number of elements
a.size

3

In [13]:
# Size in bytes of each element

a.itemsize

8

In [14]:
a[0]

1

In [15]:
a[0] = 10

In [16]:
a

array([10,  2,  3])

In [17]:
b = a * np.array([2, 0 ,2])
b

array([20,  0,  6])

## Python lists and Numpy arrays

In [21]:
lst = [1, 2, 3]
lst

[1, 2, 3]

In [22]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [23]:
lst.append(4)
lst

[1, 2, 3, 4]

In [24]:
a.append(4)

AttributeError: ignored

In [25]:
a = a + np.array([4])
a

array([5, 6, 7])

In general, the operations +, *, etc. work very different in Python lists and Numpy arrays. They operate element wize in Numpy.

## Dot product

In [26]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
dot = np.dot(a1, a2)
dot

32

In [27]:
sum1 = a1 * a2
dot = np.sum(sum1)
dot

32

In [28]:
sum1 = a1 * a2
dot = (a1 * a2).sum()
dot

32

In [29]:
dot = a1 @ a2
dot

32

## Multidimensional (nd) arrays

In [30]:
a = np.array([[1, 2], [3, 4]])
print(a.shape)

(2, 2)


In [31]:
a[0]

array([1, 2])

In [32]:
a[0][0]

1

In [33]:
a[0, 0]

1

In [34]:
a[0, :]

array([1, 2])

In [36]:
# Transpose the array
a.T

array([[1, 3],
       [2, 4]])

In [37]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
np.linalg.det(a)

-2.0000000000000004

In [39]:
np.diag(a)

array([1, 4])

## Slicing

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [41]:
a[0, 1]

2

In [43]:
a[0, :]

array([1, 2, 3, 4])

In [44]:
a[0, 1:3]

array([2, 3])

In [45]:
a[:, 0]

array([1, 5])

In [46]:
a[-1, -1]

8

In [47]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [48]:
bool_idx = a > 2
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [50]:
a[bool_idx]

array([3, 4, 5, 6])

In [51]:
a[a > 2]

array([3, 4, 5, 6])

In [52]:
np.where(a > 2, a, -1)

array([[-1, -1],
       [ 3,  4],
       [ 5,  6]])

In [53]:
a = np.array([10, 19, 30, 41, 50, 61])
a

array([10, 19, 30, 41, 50, 61])

In [54]:
b = [1, 2, 3]

In [56]:
# Fancy indexing
a[b]

array([19, 30, 41])

In [57]:
even = np.argwhere(a%2 == 0).flatten()
a[even]

array([10, 30, 50])

## Reshaping

In [59]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [60]:
a.shape

(6,)

In [62]:
# Reshape a to 2 rows and 3 columns
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a.reshape(2, 4)

ValueError: ignored

In [64]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [65]:
a[np.newaxis, :].shape

(1, 6)

## Concatenation

In [66]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [67]:
b = np.array([[5, 6]])

In [68]:
c = np.concatenate((a, b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
c = np.concatenate((a, b.T), axis=1)
c

array([[1, 2, 5],
       [3, 4, 6]])

In [72]:
# We can also use vstack and hstack to achive this
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [73]:
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
c = np.vstack((a, b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Broadcasting

In [75]:
x = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])
a = np.array([1, 0, 1])

In [76]:
x + a

array([[2, 2, 4],
       [5, 5, 7],
       [2, 2, 4],
       [5, 5, 7]])

## Functions and Axis

In [77]:
a = np.array([[7, 8, 9, 10, 11, 12, 13], [17, 18, 19, 20, 21, 22, 23]])

In [81]:
a

array([[ 7,  8,  9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21, 22, 23]])

In [78]:
a.sum()

210

In [79]:
a.sum(axis=1)

array([ 70, 140])

In [80]:
a.sum(axis=0)

array([24, 26, 28, 30, 32, 34, 36])

## Data types

In [82]:
a.dtype

dtype('int64')

In [83]:
x = np.array([1.0, 2.56])

In [84]:
x.dtype

dtype('float64')

In [86]:
x = np.array([1.0, 2.56], dtype=np.int64)
x

array([1, 2])

In [87]:
x = np.array([1.0, 2.56], dtype=np.int32)
x

array([1, 2], dtype=int32)

## Copying arrays

In [88]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [89]:
arr

array([1, 2, 3, 4, 5])

In [90]:
x

array([1, 2, 3, 4, 5])

In [91]:
arr[0] = 23

In [92]:
arr

array([23,  2,  3,  4,  5])

In [93]:
x

array([1, 2, 3, 4, 5])

## Generating arrays

In [94]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
a.dtype

dtype('float64')

In [97]:
a = np.full((2, 3), 5.0)
a

array([[5., 5., 5.],
       [5., 5., 5.]])

In [99]:
a = np.eye((3))
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [102]:
a = np.linspace(0, 10, 5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Random numbers

In [104]:
a = np.random.random((3, 2)) # uniform distribution
a

array([[0.69497455, 0.15424828],
       [0.69094185, 0.75312606],
       [0.48590024, 0.78096104]])

In [105]:
a = np.random.randn(3, 2)
a

array([[ 0.33136535,  0.50560753],
       [ 1.15617578,  0.18476499],
       [-0.38606008, -0.68406181]])

In [106]:
a = np.random.randint(3, 10, size=(3, 3))
a

array([[8, 3, 8],
       [5, 4, 5],
       [4, 6, 3]])

In [107]:
a = np.random.choice(5, size=10)
a

array([4, 4, 3, 4, 0, 3, 4, 2, 1, 2])

# Linear algebra

In [111]:
a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)

In [113]:
print(eigenvalues)
print("--------")
print(eigenvectors)

[-0.37228132  5.37228132]
--------
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
